"""readd meal_id

Revision ID: 040c16bc86b9
Revises: 3787595f2c71
Create Date: 2021-01-28 21:37:23.705285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '040c16bc86b9'
down_revision = '3787595f2c71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('meal_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'meal_id')
    # ### end Alembic commands ###
