"""remove location code

Revision ID: 56911601f764
Revises: 5498a61c8dbc
Create Date: 2020-09-10 01:02:54.934035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56911601f764'
down_revision = '5498a61c8dbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'code')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('code', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
