"""add tree_nut

Revision ID: 71e3a1e85acb
Revises: 040c16bc86b9
Create Date: 2021-02-07 20:28:57.949006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71e3a1e85acb'
down_revision = '040c16bc86b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('tree_nut', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'tree_nut')
    # ### end Alembic commands ###
