"""add shortnames

Revision ID: a06dd646ff2f
Revises: cca350e43bba
Create Date: 2020-12-27 17:08:44.893229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06dd646ff2f'
down_revision = 'cca350e43bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('shortname', sa.String(), nullable=False))
    op.alter_column('locations', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('locations', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('locations', 'shortname')
    # ### end Alembic commands ###
