"""add meal times

Revision ID: e8c7ffd550e3
Revises: f6f01a9f93dd
Create Date: 2020-09-13 14:20:06.050577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c7ffd550e3'
down_revision = 'f6f01a9f93dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('end_time', sa.String(), nullable=True))
    op.add_column('meals', sa.Column('start_time', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meals', 'start_time')
    op.drop_column('meals', 'end_time')
    # ### end Alembic commands ###
