"""init

Revision ID: f6f01a9f93dd
Revises: 
Create Date: 2020-09-12 10:22:33.758776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6f01a9f93dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('managers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ingredients', sa.String(), nullable=True),
    sa.Column('vegetarian', sa.Boolean(), nullable=True),
    sa.Column('vegan', sa.Boolean(), nullable=True),
    sa.Column('alcohol', sa.Boolean(), nullable=True),
    sa.Column('nuts', sa.Boolean(), nullable=True),
    sa.Column('shellfish', sa.Boolean(), nullable=True),
    sa.Column('peanuts', sa.Boolean(), nullable=True),
    sa.Column('dairy', sa.Boolean(), nullable=True),
    sa.Column('egg', sa.Boolean(), nullable=True),
    sa.Column('pork', sa.Boolean(), nullable=True),
    sa.Column('seafood', sa.Boolean(), nullable=True),
    sa.Column('soy', sa.Boolean(), nullable=True),
    sa.Column('wheat', sa.Boolean(), nullable=True),
    sa.Column('gluten', sa.Boolean(), nullable=True),
    sa.Column('coconut', sa.Boolean(), nullable=True),
    sa.Column('meal_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portion_size', sa.String(), nullable=True),
    sa.Column('calories', sa.String(), nullable=True),
    sa.Column('total_fat', sa.String(), nullable=True),
    sa.Column('saturated_fat', sa.String(), nullable=True),
    sa.Column('trans_fat', sa.String(), nullable=True),
    sa.Column('cholesterol', sa.String(), nullable=True),
    sa.Column('sodium', sa.String(), nullable=True),
    sa.Column('total_carbohydrate', sa.String(), nullable=True),
    sa.Column('dietary_fiber', sa.String(), nullable=True),
    sa.Column('total_sugars', sa.String(), nullable=True),
    sa.Column('protein', sa.String(), nullable=True),
    sa.Column('vitamin_d', sa.String(), nullable=True),
    sa.Column('vitamin_a', sa.String(), nullable=True),
    sa.Column('vitamin_c', sa.String(), nullable=True),
    sa.Column('calcium', sa.String(), nullable=True),
    sa.Column('iron', sa.String(), nullable=True),
    sa.Column('potassium', sa.String(), nullable=True),
    sa.Column('total_fat_pdv', sa.Integer(), nullable=True),
    sa.Column('saturated_fat_pdv', sa.Integer(), nullable=True),
    sa.Column('trans_fat_pdv', sa.Integer(), nullable=True),
    sa.Column('cholesterol_pdv', sa.Integer(), nullable=True),
    sa.Column('sodium_pdv', sa.Integer(), nullable=True),
    sa.Column('total_carbohydrate_pdv', sa.Integer(), nullable=True),
    sa.Column('dietary_fiber_pdv', sa.Integer(), nullable=True),
    sa.Column('total_sugars_pdv', sa.Integer(), nullable=True),
    sa.Column('protein_pdv', sa.Integer(), nullable=True),
    sa.Column('vitamin_d_pdv', sa.Integer(), nullable=True),
    sa.Column('vitamin_a_pdv', sa.Integer(), nullable=True),
    sa.Column('vitamin_c_pdv', sa.Integer(), nullable=True),
    sa.Column('calcium_pdv', sa.Integer(), nullable=True),
    sa.Column('iron_pdv', sa.Integer(), nullable=True),
    sa.Column('potassium_pdv', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nutrition')
    op.drop_table('items')
    op.drop_table('courses')
    op.drop_table('meals')
    op.drop_table('managers')
    op.drop_table('locations')
    # ### end Alembic commands ###
